# Generated by Django 2.2.4 on 2019-08-09 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankRecord',
            fields=[
                ('date_processed', models.DateField()),
                ('date_transaction', models.DateField()),
                ('unique_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tran_type', models.CharField(max_length=15)),
                ('reference', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-unique_id'],
            },
        ),
        migrations.CreateModel(
            name='RecordShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.PositiveSmallIntegerField(blank=True, null=True,
                                                           validators=[django.core.validators.MinValueValidator(0),
                                                                       django.core.validators.MaxValueValidator(100)])),
                ('account_holder',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.AccountHolder')),
                ('bank_record',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.BankRecord')),
            ],
            options={
                'unique_together': {('bank_record', 'account_holder')},
            },
        ),
    ]
