# Generated by Django 2.2.4 on 2019-08-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecord',
            fields=[
                ('date_processed', models.DateField()),
                ('date_transaction', models.DateField()),
                ('unique_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tran_type', models.CharField(max_length=15)),
                ('reference', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
