# Generated by Django 2.2.4 on 2019-08-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
