# Generated by Django 2.2.4 on 2019-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0002_auto_20190810_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='rounding_likelihood',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
