# Generated by Django 2.2.4 on 2019-08-16 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0004_auto_20190810_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankrecord',
            options={'ordering': ['-date_processed', '-unique_id']},
        ),
    ]
